{% set name = "curve-apps" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.zip
  sha256: 91459039c962adf9368750f872521e04c3296cc37e2a3978d87d7a1033ceac38

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - geoh5py >=0.10.0,<0.11.dev
    - geoapps-utils >=0.4.0,<0.5.dev
    - numpy >=1.26.0,<1.27.dev
    - pydantic >=2.5.2,<2.6.dev
    - scikit-image >=0.24.0,<0.25.dev
    - scipy >=1.14.0,<1.15.dev
    - tqdm >=4.66.1,<4.67.dev

test:
  imports:
    - curve_apps
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Find edges on 2D grids or vertices.'
  description: |
    Auto-detection of trends and edges in geoscientific data.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://mirageoscience-curve-apps.readthedocs-hosted.com/
  dev_url: https://github.com/MiraGeoscience/curve-apps

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
