schema_version: 1

context:
  name: curve-apps
  version: "0.3.0"
  python_min: '3.10'
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.zip
  sha256: 448f5220a3c7b1d9ebf943b9d7d32276f3b085ebda7f9fc7394e37b8142bf137

build:
  number: 0
  noarch: python
  script: 
    - export POETRY_DYNAMIC_VERSIONING_BYPASS=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py 0.12.*
    - geoapps-utils 0.6.*
    # other direct dependencies
    - numpy 1.26.* 
    - pydantic >=2.5.2, 2.*
    - scikit-image >=0.25.2, 0.25.*
    - scipy 1.14.*
    - tqdm >=4.66.1, 4.*
    - dask-core 2025.3.*
    # Dash and related dependencies
    - dash >=3.0.4, 3.*
    - dash-ag-grid >=32.3.1, 32.*
    - dash-bootstrap-components >=2.0.3, 2.*
    - dash-core-components 2.*
    - dash-daq 0.6.*
    - dash-html-components 2.*
    - dash-table 5.*
    - waitress >=3.0.2, 3.*
  run_constraints:
    - pywebview 6.*

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
        - ${{ module_name }}.peak_finder
        - dask
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/
  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py
about:
  summary: Find edges on 2D grids or vertices.
  description: |
    Auto-detection of trends and edges in geoscientific data.
    Includes the peak-finder application for the detection and grouping of time-domain
    electromagnetic (TEM) anomalies measured along flight lines.
  license: MIT
  license_file:
    - LICENSE
    - docs/source/THIRD_PARTY_SOFTWARE.rst
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/curve-apps
  documentation: https://mirageoscience-curve-apps.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
